# Global Configuration Settings
kafka_bootstrap_servers: "localhost:9094"
kafka_group_id: "syslog-consumers"
kafka_max_records_poll: 500
batch_size: 30000
processes: 4
metrics_port: 4499

# Handler Configuration
handler:
  type: "NFWareSyslogHandler"
  options: {}
    # Optional regex patterns - will use defaults if not provided
    # regex_patterns:
    #   - regex: "(?P<event>[AD]) VRF (?P<vrf_id>\\d+) INT (?P<src_ip>\\d+\\.\\d+\\.\\d+\\.\\d+) EXT (?P<x_ip>\\d+\\.\\d+\\.\\d+\\.\\d+)$"
    #     handler: "parse_address_mapping"
    #   - regex: "(?P<event>[AD]) VRF (?P<vrf_id>\\d+) (?P<protocol>\\d+) INT (?P<src_ip>\\d+\\.\\d+\\.\\d+\\.\\d+):(?P<src_port>\\d+) EXT (?P<x_ip>\\d+\\.\\d+\\.\\d+\\.\\d+):(?P<x_port>\\d+)$"
    #     handler: "parse_port_mapping"
    #   - regex: "(?P<event>[AD]) VRF (?P<vrf_id>\\d+) (?P<protocol>\\d+) INT (?P<src_ip>\\d+\\.\\d+\\.\\d+\\.\\d+):(?P<src_port>\\d+) EXT (?P<x_ip>\\d+\\.\\d+\\.\\d+\\.\\d+):(?P<x_port>\\d+) DST (?P<dst_ip>\\d+\\.\\d+\\.\\d+\\.\\d+):(?P<dst_port>\\d+) DIR (?P<direction>OUT|IN)$"
    #     handler: "parse_session_mapping"
    #   - regex: "(?P<event>[AD]) VRF (?P<vrf_id>\\d+) INT (?P<src_ip>\\d+\\.\\d+\\.\\d+\\.\\d+) EXT (?P<x_ip>\\d+\\.\\d+\\.\\d+\\.\\d+):(?P<start_port>\\d+)-(?P<end_port>\\d+)$"
    #     handler: "parse_port_block_mapping"

# Outputs Configuration
outputs:
  # TimeScaleDB Output
  - type: "TimeScaleDBOutput"
    options:
      address: "tsdb"
      port: 5432
      username: "cgnat"
      password: "password123"
      database: "cgnat"
      batch_size: 30000
  # - type: "KafkaOutput"
  #   options:
  #     bootstrap_servers: "localhost:9094"
  #     topic: "cgnat.events"
  #     key_field: "x_ip"  # Possible values: x_ip, x_port, dst_ip, dst_port, src_ip, src_port
  #     producer_extra_config: {}
  # - type: "HTTPWebhookOutput"
  #   options:
  #     url: "http://localhost/test"
  #     headers:
  #       x-api-key: default-change-me
  #     timeout: 10
  #   preprocessors:
  #     - name: filter_keys
  #       arguments:
  #         keys:
  #           - src_ip
  #           - src_port
  #           - x_ip
  #           - x_port
  #           - timestamp
  #           - dst_ip
  #           - dst_port
  #           - event
  #           - type
  #     - name: match_kvs
  #       arguments:
  #         kvs:
  #           src_ip: 192.168.1.20
  #           type: session-mapping
  # AMQP Output
  # - type: "AMQPOutput"
  #   options:
  #     host: "localhost"
  #     port: 5672
  #     username: cgnec
  #     password: cgnec