# Global Configuration Settings
kafka_bootstrap_servers: "localhost:9094"
kafka_group_id: "syslog-consumers"
kafka_max_records_poll: 500
batch_size: 30000

# Handler Configuration
handler:
  type: "NFWareSyslogHandler"
  options: {}

# Outputs Configuration
outputs:
  # TimeScaleDB Output
  - type: "TimeScaleDBOutput"
    options:
      address: "tsdb"
      port: 5432
      username: "cgnat"
      password: "password123"
      database: "cgnat"
      batch_size: 30000

  - type: "HTTPWebhookOutput"
    options:
      url: "http://localhost/test"
      headers:
        x-api-key: default-change-me
      timeout: 10
    preprocessors:
      - name: filter_keys
        arguments:
          keys:
            - src_ip
            - src_port
            - x_ip
            - x_port
            - timestamp
            - dst_ip
            - dst_port
            - event
            - type
      - name: match_kvs
        arguments:
          kvs:
            src_ip: 192.168.1.20
            type: session-mapping