services:
  kafka:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - 9094:9094
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_LISTENERS: 'INTERNAL://kafka:9092,CONTROLLER://:9093,EXTERNAL://kafka:9094'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://kafka:9094'
      
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
    - ./config.test.yaml:/app/config.yaml
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_MAX_RECORDS_POLL: 30000
      PROCESSES: 1
      METRICS_PORT: 4499