name: Run Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"

      - name: Run pytest
        run: PYTHONPATH=$(pwd) pytest